package net.Zrips.CMILib.Items;

public enum CMIMC {

    SEETHROW, STAIRS, SIGN, WALLSIGN, SPAWNEGG, EGG, SLAB, DOOR, CARPET, WOOL, MONSTEREGG, TOOL, WEAPON, ARMOR, TRAPDOOR, FENCE, FENCEGATE, PRESSUREPLATE, SKULL, SPAWNER, SHULKERBOX, AIR, POTTED, ANVIL,
    WALL, COPPER, WAXED, GLASSPANE, DYE, PLAYERHEAD, MONSTERHEAD, RAIL, BOAT, CHESTBOAT, RAFT, SAPLING, BUTTON, HOE, BED, POTION, LEATHER, HELMET, LEGGINGS, CHESTPLATE, BOOTS, PICKAXE, SHOVEL, AXE,
    TEMPLATE, DOUBLEPLANT, CANDLE, CANDLECAKE, CAKE

}
